### ISSUE TITLE
Skeleton.js tutorial

### ISSUE THREAD

**Issue by guypeer8** [cdnjs/tutorials#23]
Hi :)
I have pushed skeleton.js tutorial, and just wanted to know how can I make
it appear on cdnjs.
Thanks!

**Comment by PeterDaveHello** [comment]
Should be there soon.

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/js-skeleton
![download](https://cloud.githubusercontent.com/assets/3691490/15603913/08ef5f6c-2430-11e6-8197-a71edde4c738.png)

**Comment by guypeer8** [comment]
Very cool Peter, thanks!
