### ISSUE TITLE
Digits and units

### ISSUE THREAD

**Issue by Lengen1971** [cdnjs/tutorials#36]
Hi,
howto count up digits that have a unit like '37 %' or similar. At the moment it´s 'NAN'.

Thanx and best regards
Michael

**Comment by MattIPv4** [comment]
I'm not sure this is quite the right place for generic javascript questions, however...

Assuming you have an array of values like `37 %`, you could make use of a replace call and reduce.

Using `.replace(/\s*%$/, "")` on each string will remove any whitespace and then the percent sign from each value. `'37 %'.replace(/\s*%$/, '') === '37'`.

Once we have the numbers as clean strings, we can use a call to `parseFloat` (or `parseInt`, but using float allows for decimal places) to get them back as numbers. `parseFloat('37') === 37`.

We can then use this inside a `.reduce` call on the array to run this on each string in the array can get the total. `['37 %', '23 %'].reduce(function (prev, current) { return prev + parseFloat(current.replace(/\s*%$/, '')); }, 0)`.

Here, with each item in the array, we're doing the conversion above to change it from the string percentage to a proper number and then adding it to the previous. However, when we're doing this to the first item, there is no previous, so the `0` as the second argument in the reduce call acts as the initial previous value.

Running this reduce call, we can see that `['37 %', '23 %'].reduce(function (prev, current) { return prev + parseFloat(current.replace(/\s*%$/, '')); }, 0) === 60`.

Hope that helps :)

**Comment by MattIPv4** [comment]
Closing, no further progress.

**Comment by Lengen1971** [comment]
Hi,
I´m not questioning about javascript, i´m not that fimilar with that.

My question concerns to CounterUp library. This library should be ready to use and I expect a lot of users to count up digits with an associating unit like '%' oder 'm' (meters) someting like that. 

it seems not be possible.

Thanks.

**Comment by MattIPv4** [comment]
We don't provide support for the library we host really, you'll want to reach out to those involved in the library itself: https://github.com/bfintal/Counter-Up
