### ISSUE TITLE
Submitting tutoriap

### ISSUE THREAD

**Issue by Lightningboy24** [cdnjs/tutorials#9]
Forgive me if I'm missing something, I haven't had to do this in a while. I followed the instructions and forked, copied, wrote my tutorial. Now how are tutorials submitted? I attempted pushing from my fork to this repo but the action was denied.

**Comment by PeterDaveHello** [comment]
You of course don't have permission to push to this repo, you need to create a pull request.
See the document on GitHub:
https://help.github.com/articles/creating-a-pull-request/

**Comment by Lightningboy24** [comment]
I found it literally seconds after posting this. Sorry for wasting your time.
